const fs = require('fs');
const path = require('path');
const axios = require('axios');
const FormData = require('form-data');

async function testUploadEndpoint() {
  console.log('🚀 Running E2E HTTP Marksheet Upload Test...');
  
  const API_URL = 'http://localhost:5000';
  let token = '';

  // Step 1: Login
  try {
    console.log('🔑 Authenticating coordinator...');
    const loginRes = await axios.post(`${API_URL}/api/auth/coordinator-login`, {
      coordinatorId: 'coord_cse',
      password: 'coord123'
    });
    token = loginRes.data.token;
    console.log('✅ Authenticated successfully! Token retrieved.');
  } catch (loginErr) {
    console.error('❌ Authentication failed:', loginErr.response ? loginErr.response.data : loginErr.message);
    process.exit(1);
  }

  // Step 2: Upload
  const form = new FormData();
  form.append('file', fs.createReadStream('d:/Placement-Portal/sem 1 test.pdf'));
  form.append('semester', '1');
  form.append('jobId', 'e2e_job_' + Date.now());
  form.append('debug', 'true');

  try {
    console.log('📤 Uploading sem 1 test.pdf via authenticated endpoint...');
    const response = await axios.post(`${API_URL}/api/marksheets/upload`, form, {
      headers: {
        ...form.getHeaders(),
        'Authorization': `Bearer ${token}`
      }
    });
    console.log(`✅ Upload API response: ${response.status} OK`);
    console.log(`- Extracted count: ${response.data.extractedMarksheets ? response.data.extractedMarksheets.length : 0} marksheets`);
    
    // Read generated debug files from disk (written by Node.js express backend route)
    const debugDir = 'd:/Placement-Portal/debug';
    const missingSubjectsPath = path.join(debugDir, 'missing_subjects.json');
    if (fs.existsSync(missingSubjectsPath)) {
      const missing = JSON.parse(fs.readFileSync(missingSubjectsPath, 'utf8'));
      console.log(`\n📂 missing_subjects.json generated successfully (${missing.length} records).`);
      console.log('Sample missing records:');
      console.log(JSON.stringify(missing.slice(0, 4), null, 2));
    } else {
      console.error('❌ missing_subjects.json was NOT generated by the backend route!');
    }

    const backendPath = path.join(debugDir, 'backend.json');
    if (fs.existsSync(backendPath)) {
      console.log(`\n📂 backend.json generated successfully (${fs.statSync(backendPath).size} bytes).`);
    } else {
      console.error('❌ backend.json was NOT generated by the backend route!');
    }

  } catch (err) {
    console.error('❌ Upload API call failed:', err.response ? err.response.data : err.message);
  }
}

testUploadEndpoint();
