/**
 * Centralized registry of all supported mail and notification events.
 */
const EMAIL_EVENTS = {
    // Authentication & Accounts
    OTP_VERIFICATION: 'OTP_VERIFICATION',
    WELCOME: 'WELCOME',
    COORDINATOR_WELCOME: 'COORDINATOR_WELCOME',
    ADMIN_PROFILE_TRANSFER_OTP: 'ADMIN_PROFILE_TRANSFER_OTP',

    // Block & Unblock Operations
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
    ACCOUNT_UNBLOCKED: 'ACCOUNT_UNBLOCKED',
    COORDINATOR_BLOCKED: 'COORDINATOR_BLOCKED',
    COORDINATOR_UNBLOCKED: 'COORDINATOR_UNBLOCKED',
    STUDENT_BLOCKED_BY_ADMIN: 'STUDENT_BLOCKED_BY_ADMIN',
    STUDENT_UNBLOCKED_BY_ADMIN: 'STUDENT_UNBLOCKED_BY_ADMIN',
    STUDENT_BLOCKED_BY_COORDINATOR: 'STUDENT_BLOCKED_BY_COORDINATOR',
    STUDENT_UNBLOCKED_BY_COORDINATOR: 'STUDENT_UNBLOCKED_BY_COORDINATOR',

    // Training Operations
    TRAINING_PREFERENCE_OPEN: 'TRAINING_PREFERENCE_OPEN',
    TRAINING_SCHEDULED: 'TRAINING_SCHEDULED',
    TRAINING_ATTENDANCE_REPORT: 'TRAINING_ATTENDANCE_REPORT',
    TRAINING_ATTENDANCE_SUMMARY: 'TRAINING_ATTENDANCE_SUMMARY',

    // Certificate Operations
    CERTIFICATE_APPROVED: 'CERTIFICATE_APPROVED',
    CERTIFICATE_REJECTED: 'CERTIFICATE_REJECTED',

    // Placement Drive & Recruitment Operations
    STUDENT_SHORTLISTED: 'STUDENT_SHORTLISTED',
    ROUND_PASSED: 'ROUND_PASSED',
    NEXT_ROUND: 'NEXT_ROUND',
    STUDENT_REJECTED: 'STUDENT_REJECTED',
    FINAL_SELECTED: 'FINAL_SELECTED',
    DRIVE_ATTENDANCE_SUMMARY: 'DRIVE_ATTENDANCE_SUMMARY',
    DRIVE_ROUND_SUMMARY: 'DRIVE_ROUND_SUMMARY',

    // Offer Letter & Student Decision
    OFFER_LETTER: 'OFFER_LETTER',
    OFFER_RESPONSE: 'OFFER_RESPONSE'
};

module.exports = EMAIL_EVENTS;
