/**
 * Centralized registry of all supported mail and notification events.
 */
const EMAIL_EVENTS = {
    OTP_VERIFICATION: 'OTP_VERIFICATION',
    WELCOME: 'WELCOME',
    STUDENT_SHORTLISTED: 'STUDENT_SHORTLISTED',
    ROUND_PASSED: 'ROUND_PASSED',
    NEXT_ROUND: 'NEXT_ROUND',
    STUDENT_REJECTED: 'STUDENT_REJECTED',
    FINAL_SELECTED: 'FINAL_SELECTED',
    CERTIFICATE_APPROVED: 'CERTIFICATE_APPROVED',
    CERTIFICATE_REJECTED: 'CERTIFICATE_REJECTED',
    DRIVE_ATTENDANCE_SUMMARY: 'DRIVE_ATTENDANCE_SUMMARY',
    TRAINING_ATTENDANCE_SUMMARY: 'TRAINING_ATTENDANCE_SUMMARY'
};

module.exports = EMAIL_EVENTS;
